### ISSUE TITLE
the one probe crash

### ISSUE THREAD

**Issue by FearAK** [the9grounds/AE-Additions#103]
Idk why but using this mod alongside theoneprobe seems to crash on launch.

[crash-2022-10-05_16.12.46-fml.txt](https://github.com/the9grounds/AE-Additions/files/9717425/crash-2022-10-05_16.12.46-fml.txt)

**Comment by DeleteMetaInf** [comment]
I came here to report the same issue. Disablign AE Additions lets the game launch normally.

**Crash report:** https://pastebin.com/raw/rMpXh2Lt

### Versions
* **Minecraft:** 1.18.2
* **Forge:** 40.1.80 (latest)
* **AE Additions:** 3.2.2 (latest)
* **The One Probe:** 5.1.2 (latest)

**Comment by DeleteMetaInf** [comment]
[According to McJty](https://github.com/McJtyMods/TheOneProbe/issues/586#issuecomment-1269269280), this is a bug in AE Additions.

**Comment by DeleteMetaInf** [comment]
Thanks for the fix! 🎉
