### ISSUE TITLE
(1.18.2-Latest) Crash with MEGACells Latest?

### ISSUE THREAD

**Issue by Phweeeee** [the9grounds/AE-Additions#104]
When updating my AE2 11.6.0/1 and MEGACells 1.4.0, My game crashes and it blames ae2additions (Your mod, not the other AeAdditions). Can you look into this?

Report: https://paste.gg/p/anonymous/45b0b92be5a64c23941d0d190a89cac7

The Mod in Question: https://github.com/62832/MEGACells

**Comment by luffykick** [comment]
literally just came here to report this also..

**Comment by Phweeeee** [comment]
> literally just came here to report this also..

Lol, I've been having a rough day with AE2 and updates. Hopefully this is the last issue I find

**Comment by Phweeeee** [comment]
It has started crashing again under MEGACells 1.4.2. Check it out:

https://paste.gg/p/anonymous/46074990a82c40adb3a098b9b56c261c

**Comment by Phweeeee** [comment]
Has this been looked into?

**Comment by Beachman4** [comment]
@Phweeeee Okay, I have a fix for this that I will be pushing soon. Can you try it out for me and let me know if it works for you?

**Comment by Phweeeee** [comment]
I hope I didn't come off as hostile with my comment  before. It's all good.  Hopefully you're feeling better and are ready to tackle some of the other 1.18.2 bugs!

As for the build. It's now compatible with MEGACells 1.4.2.
