### ISSUE TITLE
Clicking 'save' in the transceiver GUI crashes the client

### ISSUE THREAD

**Issue by Porcy** [the9grounds/AE-Additions#105]
Tried to add a new channel on my newly placed transceiver. Got this instead :(
[crash-2022-10-16_18.42.13-client.txt](https://github.com/the9grounds/AE-Additions/files/9795850/crash-2022-10-16_18.42.13-client.txt)

**Comment by zeziba** [comment]
Have the same issue, need to add that I only get the crash if the transceiver gui does not have any channel selected or has not been selected yet.

So to reproduce you just place one down, open gui and hit save.

TNP 6 Limitless on 1.19

**Comment by Beachman4** [comment]
I'll be getting to this soon. Sorry about the wait.

**Comment by expdani** [comment]
Got the same issue. I can't seem to normally interact with the block anymore because it's empty and not seeing any channels. Also creating and switching doesn't work.

**Comment by Beachman4** [comment]
I believe I resolved this issue with this commit: https://github.com/the9grounds/AE-Additions/commit/c4632fc906a494431036740e28fdedeee807006a

Do you have a crash log for the issue you're having @expdani?
