### ISSUE TITLE
[1.19.2] NullPointerException

### ISSUE THREAD

**Issue by HugPhiluu** [the9grounds/AE-Additions#114]
Hiya!
I have an issue on my AllTheMods 8 Server.
I am running the modpack version 1.0.11 which is using AEAdditions 4.0.3 of your mod (Forge - AEAdditions-1.19.2-4.0.3.jar).

Every now and then, when I right click a "ME Wireless Transceiver" I tend to get disconnected from my server and see the following screen.
![image](https://user-images.githubusercontent.com/97440819/219952358-6f4462e0-63d7-471c-992a-7b5f8ced1d94.png)

It makes using that block very difficult as it just sometimes works as intended :/
I'd be happy to supply logs, but I can't seem to find any.

**Comment by LordBobbert** [comment]
I'm getting the same error. I've removed all my existing terminals. Reloaded the game. Taken removed my claim chunks. Nothing works.

**Comment by Beachman4** [comment]
Could I get any logs of this happening?

**Comment by HugPhiluu** [comment]
Right after right-clicking the ME Wireless Transceiver

```
[21:43:52] [Netty Client IO #1/WARN] [co.co.Connectivity/]: java.lang.NullPointerException
[21:43:52] [Netty Client IO #1/WARN] [co.co.Connectivity/]: Packet not registered: ClientboundDisconnectPacket
[21:43:52] [Netty Client IO #1/WARN] [co.co.Connectivity/]: io.netty.handler.codec.EncoderException: java.io.IOException: Can't serialize unregistered packet
```

**Comment by LordBobbert** [comment]
Any update on this? This just started happening to me on another server.

**Comment by Beachman4** [comment]
Not exactly, I've been trying to track down this issue, but it's difficult because the error log doesn't really explain why it's happening.

**Comment by NullOrNaN** [comment]
Here's how I was able to reproduce this myself with some testing after a few players reported it.
1. Create a channel either public or private.
2. Delete channel
3. Save it when there's no other channels that you can see
4. Crash on use

**Comment by Beachman4** [comment]
Thanks for the reproduction. I've been able to experience the issue locally and I'll get working on a fix now.

**Comment by Beachman4** [comment]
I uploaded a new version to curseforge, can you see if you still have issue now?

Please reopen if you do
