### ISSUE TITLE
wireless transciver crashes when I (try to) save a channel

### ISSUE THREAD

**Issue by sadanslargehole** [the9grounds/AE-Additions#116]
crash log
https://mclo.gs/H9FkggG
I am playing ATM8 on a locally hosted server

**Comment by sadanslargehole** [comment]
I now cannot even open it, it kicks me out with a null pointer exception whenever i open the gui

**Comment by nerd-king** [comment]
I have the same issue.  To reproduce, open the GUI, type in a name (do not hit the plus sign...yes I realize you're supposed to), hit save.  Null pointer crash.

**Comment by RadegasTCZ** [comment]
> I have the same issue. To reproduce, open the GUI, type in a name (do not hit the plus sign...yes I realize you're supposed to), hit save. Null pointer crash.

I can just place the transceiver right click on in and instantly get disconnected :D

**Comment by Beachman4** [comment]
[jars.zip](https://github.com/the9grounds/AE-Additions/files/11996695/jars.zip)

Can you use the jar file from this zip and tell me if the issue has been resolved?

**Comment by Beachman4** [comment]
I uploaded a new version to curseforge, can you see if you still have issue now?

Please reopen if you do
