### ISSUE TITLE
Wireless transceivers not saving

### ISSUE THREAD

**Issue by EnforcerTTV** [the9grounds/AE-Additions#120]
Issue: Every time I launch my server the wireless transceivers decide to reset, NOT all but a good amount of them do.
MC Version: 1.19.2
Forge: 43.2.4
AE2 Version: 12.9.2
AE Additions Version: 4.0.3
Steps to Reproduce:
Stop minecraft server,
Launch minecraft server and settings won't be saved on some transceivers. I also can't delete any of the channels.

**Comment by sjs262** [comment]
This happens to me as well, super annoying!

**Comment by Beachman4** [comment]
I'm unsure if I've fixed this, however, I'd live to give you guys a build to see if it's working now

**Comment by Beachman4** [comment]
[jars.zip](https://github.com/the9grounds/AE-Additions/files/11996695/jars.zip)

Can you try the jar file in this zip and tell me if it solves it?

**Comment by EnforcerTTV** [comment]
I'll check it out tomorrow when I have time, Hopefully it fixes the issues I've had with it. This mod is sooo valuable to have with ae2 that dealing with the issues "as long as it isn't hard crashing every 10 seconds" is kinda worth it.

**Comment by Beachman4** [comment]
Awesome! Thanks for double checking and ensuring the issues were resolved.

**Comment by EnforcerTTV** [comment]
Any idea when the official release of this jar will be posted? Ill be using the experimental one for now but just so i know :)

**Comment by Beachman4** [comment]
It should already be on curseforge right now

**Comment by EnforcerTTV** [comment]
Weird considering i tried 4.0.4 which is on curseforge and it didnt let me delete channels but the rar you put here worked

**Comment by EnforcerTTV** [comment]
Also I do have bad news, Within more testing and a few more server restarts. Some of the wireless transceivers still reset, And they won't be subscribed anymore.

**Comment by EnforcerTTV** [comment]
Finally fixed lets go :)

**Comment by EnforcerTTV** [comment]
Finally fixed lets go :)
