### ISSUE TITLE
No Gas support 1.19.2

### ISSUE THREAD

**Issue by SikiciBebek** [the9grounds/AE-Additions#122]
<img width="570" alt="image" src="https://github.com/the9grounds/AE-Additions/assets/98269183/89a3ba57-6731-46e4-9822-1feac70b4d7f">

Any ideas how to fix that? or what i need to add?

**Comment by Beachman4** [comment]
As long as you have mekanism in your modpack it should pick it up.

The super storage cell relies on what item types AE has registered in it's system, so as long as AE is picking up that you have Mekanism(i.e. it allows you to do chemical i/o) then it should work

**Comment by SikiciBebek** [comment]
Oh lol
At the beginning it didnt work
after restarting my game it did
ty! ^^
