### ISSUE TITLE
[1.20.1-Forge] Mod crashes when attempting to load on a server.

### ISSUE THREAD

**Issue by Gbergz** [the9grounds/AE-Additions#126]
Title^

**Versions:**
Forge: 47.1.3
MC: 1.20.1
AE Additions: 5.0.0
AE2: 15.0.4-beta

Crash-Report: https://gist.githubusercontent.com/Gbergz/1b702b1c718966f4eea8b2ea7a6bc183/raw/603d38851f051e6f3c1552299cbe97692b21106a/gistfile1.txt

**Comment by Beachman4** [comment]
I have just released a new version to curseforge, it'll be up as soon as they approve it.
