### ISSUE TITLE
[1.20.1] Me Wireless Transceiver channel list is broken

### ISSUE THREAD

**Issue by programgames** [the9grounds/AE-Additions#133]
When you have more than one channel available, every channels shows in only one line : 
![2023-08-17_10 06 24](https://github.com/the9grounds/AE-Additions/assets/18596429/13f5d7a8-5714-459b-b850-0826e291f104)

**Comment by Swat99Swat** [comment]
Really looking forward to the fix of this thing. And possible improvements to this block.

**Comment by J4YD3D** [comment]
Youre also incapable of deleting the channels, making the block outright unusable unfortunately

**Comment by Beachman4** [comment]
Thanks for reporting this. I'll take a look at this sometime today

**Comment by Unbistrackted** [comment]
![image](https://github.com/the9grounds/AE-Additions/assets/112902220/b7135135-b390-4b30-bd4a-24649312915f)
![image](https://github.com/the9grounds/AE-Additions/assets/112902220/4926747c-56ce-44ee-93ec-e0639c98ef07)

Block stops working after spamming "Acess mode" and/or spam create new networks... Is there any way to delete those 'ghost' channels without the block GUI?

**Comment by kirkstanovich** [comment]
Is there any update on this? I’m also running into this issue on ATM9 and it’s unfortunately preventing me from some AE2 expansion.

**Comment by wu452148993** [comment]
I compared the codes of 1.19.2 and 1.20.1 and found the following errors:
MEWirelessTransceiverScreen.kt
        channels.forEachIndexed { index, channelInfo ->
            val channelField = this.channelFields[channelInfo]
            if (channelField != null) {
                channelField.updateValues(shouldShowChannel(index), selectedChannel == channelInfo, channelY)
                channelField.render(guiGraphics, 0, 0, 0f)
            }
        }
==>
        channels.forEachIndexed { index, channelInfo ->
            val channelField = this.channelFields[channelInfo]
            if (channelField != null) {
                channelField.updateValues(shouldShowChannel(index), selectedChannel == channelInfo, channelY)
                channelField.render(guiGraphics, 0, 0, 0f)
                channelY += 12
            }
        }

**Comment by AnthonyOGorman** [comment]
Issue persists on MC1.20.1 AE-Additions 5.0.5 
![image](https://github.com/the9grounds/AE-Additions/assets/1390977/410218ce-eb3c-46f5-9460-b061ffe7c704)
Unable to create new channels, however even though no channels are showing, existing transceivers are still connected.

**Comment by Dbz9** [comment]
Same issue on ATM8 last version
