### ISSUE TITLE
Me Wireless Transceiver Crash

### ISSUE THREAD

**Issue by NightGamer667** [the9grounds/AE-Additions#134]
Whenever I want to create a chanel, the game crashes, but it worked great before 
and it doesn't show the old chanel either
![Screenshot (133)](https://github.com/the9grounds/AE-Additions/assets/40357253/a769fb74-443c-4192-984d-a3ba66c3b6f8)
![Screenshot (132)](https://github.com/the9grounds/AE-Additions/assets/40357253/e7762671-0658-43ff-8c17-bf2a244941ba)

**Comment by Beachman4** [comment]
Please let me know if you still encounter issues with this. I am just about to push a new update with some minor fixes to the gui
