### ISSUE TITLE
Wireless Transceiver not working

### ISSUE THREAD

**Issue by CamaroKing59** [the9grounds/AE-Additions#150]
I'm currently play TNP limitless 7. I can not use the wireless transceiver on my server but I can on singleplayer. basically what happens is when on my server I try to add a channel it will not add it just disappears. but if I try it in singleplayer the channels are added. I've also tried inside and outside of claimed areas.

Minecraft version: 1.20.1
Mod Version: 5.0.5

**Comment by TheTerribleT** [comment]
I am experiencing the same thing. I noticed in Singleplayer I can also not delete any of the channels I created. 

Just another thing I thought I would point out.

**Comment by MSandro** [comment]
I am playing ATM9 there it works, but I can confirm the problem with the delete button, it does not work.

**Comment by Beachman4** [comment]
Can you provide reproduction steps on a fresh world?

I tried to replicate this and I'm able to delete channels

**Comment by Beachman4** [comment]
Correction, I was able to reproduce a delete button issue where if you press the button, it isn't removed from the list, instead you need to close the menu and reopen it for it to be deleted.

I will push a fix for that issue soon
