### ISSUE TITLE
Cell Workbench filters do not work for fluid storage above 256k

### ISSUE THREAD

**Issue by sakuraimikoto33** [the9grounds/AE-Additions#19]
Cell Workbench filters do not work for fluid storage above 256k 
![2021-06-25_05 13 56](https://user-images.githubusercontent.com/45408242/123327165-154a1a80-d575-11eb-8661-351149274138.png)
![2021-06-25_05 14 19](https://user-images.githubusercontent.com/45408242/123327172-18450b00-d575-11eb-824b-4b9c22dd2371.png)
![2021-06-25_05 16 04](https://user-images.githubusercontent.com/45408242/123327188-1c712880-d575-11eb-97a8-b162c446d80e.png)
![2021-06-25_05 16 13](https://user-images.githubusercontent.com/45408242/123327192-1da25580-d575-11eb-885c-c5650830dd97.png)

**Comment by Beachman4** [comment]
Hey there, I've discovered the issue and I'll start working on fixing it.

**Comment by Beachman4** [comment]
I'll push up a version that fixes this.

Looks like the original creators didn't get around to finishing this, looks like they started it, just didn't get done with it.

**Comment by Beachman4** [comment]
Also, I know Gas cells don't work either and I'll fix that soon as well.
