### ISSUE TITLE
[1.12.2] Crash 

### ISSUE THREAD

**Issue by SpeeeDCraft** [the9grounds/AE-Additions#40]
If you put a bucket of liquid in the liquid autofiller, minecraft will crash.
[crash-2021-08-18_10.12.33-client.txt](https://github.com/the9grounds/AE-Additions/files/7004447/crash-2021-08-18_10.12.33-client.txt)

**Comment by Beachman4** [comment]
I'll be deploying this fix to curseforge soon.

Thanks for the report!

**Comment by SpeeeDCraft** [comment]
Thanks :D
