### ISSUE TITLE
AE Additions for AE2 Fabric

### ISSUE THREAD

**Issue by Frankiscophil** [the9grounds/AE-Additions#42]
Hello! I've been playing the most recent AE2 Fabric version and always wondered if there would be an Extra Cells update to govalong with it. Lookingthrough the internet for a bit, I came across this. From what I've seen, it is very cool and I saw that you plan to update this to 1.16 and hopefully above. I would like to ask if down the line, would there would be a Fabric version of this mod to accompany the Fabric versions of AE2? I would like to hope so but I can imagine it would be difficult alone to update this mod to Forge. Nonetheless, thank you for making this mod and continuing the legacy of Extra Cells in a way.

**Comment by Beachman4** [comment]
That's a good question. I haven't looked too much at Fabric, but if AE2 supports Fabric, I'm sure along the way I'll make a Fabric version. I know there's a growing number of people who use it and I wouldn't want to leave those people out to dry :)

I'll keep this issue open to remind myself when I get done with the Forge 1.16 port.

**Comment by Beachman4** [comment]
Gonna close this as I have ported AE Additions to Forge and Fabric for 1.18.2!
