### ISSUE TITLE
Duplication glitch with Wireless Fluid termial.

### ISSUE THREAD

**Issue by GDVE** [the9grounds/AE-Additions#46]
I use all last versions of mods (AE, AE-Additions, Mekanism) avaible at curseforge.

Method:
https://youtu.be/e9RRUJTAnuE

**Comment by Beachman4** [comment]
Thanks for the report! I'll be looking into this today

**Comment by Beachman4** [comment]
@GDVE I just released this fix to curseforge under version Beta 1.3.3. Please let me know if the issue is fixed and then I'll fully release it

**Comment by PandaEzWin** [comment]
> 

The problem has been fixed verified.
Thanks for the quick fix :)
