### ISSUE TITLE
Redstone Card doesn't work in Gas IO Buses

### ISSUE THREAD

**Issue by XenInterloper** [the9grounds/AE-Additions#57]
Currently using version 1.3.4 on 1.12.2. The Gas IO buses on their own work just fine, but I am trying to use a Redstone Card in them and it is having no effect, regardless of which setting the redstone card is on. I have tried giving them a signal using a Gas Level Emitter and a normal redstone repeater; neither does anything. 

This seems to be an issue inherent to the original Extra Cells 2, as it and every other fork I've tried using has the same issue. Other than this, my gas system has worked perfectly.

**Comment by Beachman4** [comment]
So you're basically just trying to turn toggle the i/o based on on a Redstone signal, like you would with the regular item i/o?

**Comment by XenInterloper** [comment]
Yeah. I have a level emitter that should be turning off an import bus if there's already a certain amount of the gas in the system. Exactly the same as with the normal item and fluid systems. But as I said the import bus with the redstone card in it isn't responding to any redstone signal I give it

**Comment by Beachman4** [comment]
Okay, I'll look into this today

**Comment by Beachman4** [comment]
I have fixed this and will release it today.

**Comment by XenInterloper** [comment]
Awesome! Thank you for fixing this!
