### ISSUE TITLE
[1.18.2] Server Crash upon startup

### ISSUE THREAD

**Issue by aking4125** [the9grounds/AE-Additions#62]
Hello,

I saw this mod updated to 1.18.2 (Though the changelog mentions "_Initial 1.16.5 release_"). Client seems to work correctly but upon loading the mod on a dedicated server, the server crashes with the following crash report: [crash-2022-05-27_19.22.58-fml.txt](https://github.com/the9grounds/AE-Additions/files/8790065/crash-2022-05-27_19.22.58-fml.txt)

Here are the two log files if anything: 
[latest.log](https://github.com/the9grounds/AE-Additions/files/8790066/latest.log)
[debug.log](https://github.com/the9grounds/AE-Additions/files/8790067/debug.log)

Removing this mod fixes the problem and the server loads normally. Any ideas?

**Comment by Beachman4** [comment]
@aking4125 Yeah sorry, I haven't changed the changelog. Usually it gets populated automatically via github stuff, but some issue is preventing that. Give me a few minutes and I'll figure this out

**Comment by aking4125** [comment]
@Beachman4 Oh wow. That's a super speedy response!

I'm sorry about this. No worries just wanted to at least report it!

**Comment by Beachman4** [comment]
@aking4125 I have fixed the issue and pushed up a new version to curseforge, they should approve it here in the next few minutes. Thanks for the report!
