### ISSUE TITLE
[1.18.2] Crash when existing world is done booting.

### ISSUE THREAD

**Issue by Gbergz** [the9grounds/AE-Additions#65]
Title^
Added mod to an existing world, and now it crashes when world is done loading. (preparing spawn area).

Minecraft: 1.18.2
Forge: 40.1.30
AE2: 11.0.0 | https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3792686
AE Additions: 3.0.4 | https://www.curseforge.com/minecraft/mc-mods/ae-additions-extra-cells-2-fork/files/3808530

Crash-Report: https://gist.github.com/Gbergz/3de71d4089f09ddb1663ba08fb8a0dd3

**-** Gbergz

**Comment by Beachman4** [comment]
Looking into this now @Gbergz

**Comment by Beachman4** [comment]
I've identified the issue @Gbergz. I'll be pushing out an update soon. With this update though, will come a new storage cell(Super Storage Cell), so be on the lookout for that 👀

**Comment by Gbergz** [comment]
Is this being uploaded to CurseForge too?
Maybe CF is being slow.. 😅

**Comment by Beachman4** [comment]
@Gbergz Apologies, I had to step out. I just triggered the release. Please let me know if you have any other issues
