### ISSUE TITLE
[1.12.2] Cannot load old worlds after removal of mekanism

### ISSUE THREAD

**Issue by RedRaspberry** [the9grounds/AE-Additions#67]
crash report attached. Recently removed mekanism from the pack I'm working on and could not load my usual testing world.
[crash-2022-06-01_22.28.07-server.txt](https://github.com/the9grounds/AE-Additions/files/8820073/crash-2022-06-01_22.28.07-server.txt)

**Comment by Beachman4** [comment]
I'm releasing a 1.3.7 that fixes this

**Comment by RedRaspberry** [comment]
well that was fast! thanks so much
