### ISSUE TITLE
gas export and import bus error

### ISSUE THREAD

**Issue by PengyTheGamer** [the9grounds/AE-Additions#68]
When attempting to remove a gas from the ME Gas Import Bus and Export Bus, it won't get removed and if you have VanillaFix installed it creates a crash report.

**Comment by Beachman4** [comment]
@PengyTheGamer Which version are you on?

**Comment by PengyTheGamer** [comment]
the newest 1.12.2 version, AEAdditions-1.12.2-1.3.7, and here https://pastebin.com/V5HkTUjJ

**Comment by PengyTheGamer** [comment]
thanks, i'm glad for the fast response and maintaining of extracells, it's just a bug i came across when playing around with the gas support
