### ISSUE TITLE
Fabric Issue with latest Applied Energistics

### ISSUE THREAD

**Issue by FluffyBumblebees** [the9grounds/AE-Additions#70]
I noticed there was an update on forge to patch this, but fabric hasn't been given this patch yet.
[latest.log](https://github.com/the9grounds/AE-Additions/files/8844294/latest.log)

**Comment by Beachman4** [comment]
Hey there, I'll get to this later today. I need to port my other features to fabric as well

**Comment by FluffyBumblebees** [comment]
Thanks for the response! This is a great mod, thanks for supporting fabric.

**Comment by Beachman4** [comment]
I've fixed this. I've also added my super storage cells to this release as well
