### ISSUE TITLE
[1.18.2 - 3.1.0] Crash at startup - AE Additions (ae2additions) has failed to load correctly

### ISSUE THREAD

**Issue by realTIMematrix** [the9grounds/AE-Additions#77]
Hi,

I'm creating my owm modpack and I recognized a crash after updating the Mod: MEGACells to version 1.3.0.

The issue says that AE Additions produces the error, but downgraded to MEGACells-1.2.1.jar works fine.

	Mod File: AEAdditions-1.18.2-3.1.0.jar
	Failure message: AE Additions (ae2additions) has failed to load correctly
		java.lang.NoSuchFieldError: CELL_COMPONENT_1M
	Mod Version: 3.1.0
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchFieldError: CELL_COMPONENT_1M

I don't know if the issue is in your mod or in the mod mega cells.

[crash-report](https://pastebin.com/KaJBxVLU)

Forge: 40.1.54
Minecraft: 1.18.2

Mods:
AEAdditions-1.18.2-3.1.0.jar
MEGACells-1.3.0.jar

**Comment by Beachman4** [comment]
It appears that updating mega cells was enough to fix this. It'll go out in the next release
