### ISSUE TITLE
Incompatible with Modern UI

### ISSUE THREAD

**Issue by StarskyXIII** [the9grounds/AE-Additions#84]
When enable Modern Text Engine of Modern UI, it will cause text of Wireless Transceiver disappear.

Test Environment:
Forge 40.1.68
Applied Energistics2 v11.1.4
AE Additions v3.2.0
[Modern UI](https://www.curseforge.com/minecraft/mc-mods/modern-ui) v3.5.0.109

Disabled Modern Text Engine
![image](https://user-images.githubusercontent.com/71606873/179885763-4b407f9f-998a-4028-9aa7-895ce37ee92b.png)

Enabled Modern Text Engine
![image](https://user-images.githubusercontent.com/71606873/179885677-226b35dc-63c4-4c02-9685-b189362c5535.png)

**Comment by BloCamLimb** [comment]
https://github.com/the9grounds/AE-Additions/blob/master/src/main/kotlin/com/the9grounds/aeadditions/client/gui/MEWirelessTransceiverScreen.kt#L78
You passed alpha to 1, so it's nearly transparent. You should use alpha = 0 (will be adjusted to 255) or directly use alpha = 255
