### ISSUE TITLE
Weird behaviour when putting together CPU Multiblocks

### ISSUE THREAD

**Issue by v-tron** [the9grounds/AE-Additions#91]
When a 65k crafting storage is placed on an active cable the block gets broken immediately. Also when placing the crafting storage as the last block in a multiblock structure that is already connected to the network on one side the crafting storage block also breaks immediately. Putting together the CPU only works if you complete the multiblock first and then connect a cable to it. This behaviour is different from the standard AE2 where you can just place any crafting storage block and it just works. 

This might also be happening with the other crafting storage cells of this mod but I didn't test that.

**Comment by bcrotty** [comment]
This is happening for me too on 1.19 with ATM8. The behavior doesn't happen with the 16M one, only the 65M.

**Comment by Beachman4** [comment]
Can you try now? I'm not having this happen on my end. Please reopen if it's still happening
